insert into reviews values(	10326	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10327	,'	Internet Explorer	','	Mobile	','	not happy	');
insert into reviews values(	10328	,'	Mozilla	','	Tablet	','	not happy	');
insert into reviews values(	10329	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10330	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10331	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10332	,'	Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10333	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10334	,'	Internet Explorer	','	Desktop	','	happy	');
insert into reviews values(	10335	,'	Chrome	','	Tablet	','	not happy	');

insert into reviews values(	10337	,'	IE	','	Mobile	','	happy	');
insert into reviews values(	10338	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10339	,'	Internet Explorer	','	Desktop	','	happy	');
insert into reviews values(	10340	,'	Chrome	','	Desktop	','	happy	');
insert into reviews values(	10341	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10342	,'	Mozilla	','	Tablet	','	not happy	');
insert into reviews values(	10343	,'	Google Chrome	','	Desktop	','	not happy	');
insert into reviews values(	10344	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10345	,'	Mozilla	','	Desktop	','	not happy	');
insert into reviews values(	10346	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10347	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10348	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10349	,'	Chrome	','	Desktop	','	happy	');
insert into reviews values(	10350	,'	Chrome	','	Desktop	','	happy	');
insert into reviews values(	10351	,'	Opera	','	Mobile	','	not happy	');
insert into reviews values(	10352	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10353	,'	Mozilla Firefox	','	Desktop	','	happy	');
insert into reviews values(	10354	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10355	,'	Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10356	,'	Mozilla	','	Tablet	','	not happy	');
insert into reviews values(	10357	,'	Mozilla Firefox	','	Tablet	','	happy	');
insert into reviews values(	10358	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10359	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10360	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10361	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10362	,'	InternetExplorer	','	Desktop	','	not happy	');
insert into reviews values(	10363	,'	Chrome	','	Tablet	','	happy	');
insert into reviews values(	10364	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10365	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10366	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10367	,'	Internet Explorer	','	Mobile	','	happy	');
insert into reviews values(	10368	,'	Edge	','	Tablet	','	happy	');
insert into reviews values(	10369	,'	Chrome	','	Desktop	','	happy	');
insert into reviews values(	10370	,'	Internet Explorer	','	Desktop	','	happy	');
insert into reviews values(	10371	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10372	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10373	,'	Chrome	','	Mobile	','	happy	');
insert into reviews values(	10374	,'	Internet Explorer	','	Mobile	','	happy	');
insert into reviews values(	10375	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10376	,'	Mozilla Firefox	','	Mobile	','	happy	');
insert into reviews values(	10377	,'	Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10378	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10379	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10380	,'	IE	','	Desktop	','	happy	');
insert into reviews values(	10381	,'	Chrome	','	Desktop	','	happy	');
insert into reviews values(	10382	,'	Mozilla Firefox	','	Mobile	','	happy	');
insert into reviews values(	10383	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10384	,'	Chrome	','	Desktop	','	happy	');
insert into reviews values(	10385	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10386	,'	Google Chrome	','	Desktop	','	happy	');
insert into reviews values(	10387	,'	IE	','	Mobile	','	not happy	');
insert into reviews values(	10388	,'	Google Chrome	','	Desktop	','	happy	');
insert into reviews values(	10389	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10390	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10391	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10392	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10393	,'	Mozilla Firefox	','	Mobile	','	happy	');
insert into reviews values(	10394	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10395	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10396	,'	Safari	','	Mobile	','	happy	');
insert into reviews values(	10397	,'	Chrome	','	Tablet	','	happy	');
insert into reviews values(	10398	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10399	,'	Internet Explorer	','	Mobile	','	not happy	');
insert into reviews values(	10400	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10401	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10402	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10403	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10404	,'	Opera	','	Desktop	','	happy	');
insert into reviews values(	10405	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10406	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10407	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10408	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10409	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10410	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10411	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10412	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10413	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10414	,'	Google Chrome	','	Desktop	','	happy	');
insert into reviews values(	10415	,'	Internet Explorer	','	Mobile	','	happy	');
insert into reviews values(	10416	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10417	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10418	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10419	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10420	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10421	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10422	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10423	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10424	,'	IE	','	Mobile	','	happy	');
insert into reviews values(	10425	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10426	,'	Mozilla Firefox	','	Mobile	','	happy	');
insert into reviews values(	10427	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10428	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10429	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10430	,'	Internet Explorer	','	Mobile	','	happy	');
insert into reviews values(	10431	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10432	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10433	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10434	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10435	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10436	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10437	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10438	,'	Chrome	','	Tablet	','	happy	');
insert into reviews values(	10439	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10440	,'	IE	','	Desktop	','	happy	');
insert into reviews values(	10441	,'	Google Chrome	','	Desktop	','	happy	');
insert into reviews values(	10442	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10443	,'	Google Chrome	','	Desktop	','	not happy	');
insert into reviews values(	10444	,'	Safari	','	Desktop	','	not happy	');
insert into reviews values(	10445	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10446	,'	Opera	','	Tablet	','	happy	');
insert into reviews values(	10447	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10448	,'	Safari	','	Desktop	','	happy	');
insert into reviews values(	10449	,'	IE	','	Desktop	','	happy	');
insert into reviews values(	10450	,'	Chrome	','	Mobile	','	happy	');
insert into reviews values(	10451	,'	Mozilla	','	Tablet	','	not happy	');
insert into reviews values(	10452	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10453	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10454	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10455	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10456	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10457	,'	InternetExplorer	','	Tablet	','	happy	');
insert into reviews values(	10458	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10459	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10460	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10461	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10462	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10463	,'	Mozilla Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10464	,'	Google Chrome	','	Mobile	','	not happy	');
insert into reviews values(	10465	,'	Google Chrome	','	Tablet	','	not happy	');
insert into reviews values(	10466	,'	Mozilla	','	Tablet	','	not happy	');
insert into reviews values(	10467	,'	Google Chrome	','	Desktop	','	not happy	');
insert into reviews values(	10468	,'	Mozilla Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10469	,'	Mozilla Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10470	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10471	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10472	,'	Chrome	','	Tablet	','	happy	');
insert into reviews values(	10473	,'	Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10474	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10475	,'	Google Chrome	','	Tablet	','	happy	');
insert into reviews values(	10476	,'	Mozilla	','	Desktop	','	not happy	');
insert into reviews values(	10477	,'	Edge	','	Tablet	','	happy	');
insert into reviews values(	10478	,'	Google Chrome	','	Desktop	','	happy	');
insert into reviews values(	10479	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10480	,'	Mozilla Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10481	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10482	,'	Mozilla Firefox	','	Tablet	','	happy	');
insert into reviews values(	10483	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10484	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10485	,'	IE	','	Tablet	','	happy	');
insert into reviews values(	10486	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10487	,'	Internet Explorer	','	Desktop	','	happy	');
insert into reviews values(	10488	,'	Google Chrome	','	Tablet	','	happy	');
insert into reviews values(	10489	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10490	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10491	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10492	,'	IE	','	Desktop	','	happy	');
insert into reviews values(	10493	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10494	,'	Mozilla	','	Mobile	','	not happy	');
insert into reviews values(	10495	,'	Mozilla	','	Mobile	','	not happy	');
insert into reviews values(	10496	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10497	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10498	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10499	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10500	,'	Mozilla Firefox	','	Mobile	','	happy	');
insert into reviews values(	10501	,'	IE	','	Mobile	','	not happy	');
insert into reviews values(	10502	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10503	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10504	,'	Chrome	','	Tablet	','	happy	');
insert into reviews values(	10505	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10506	,'	Mozilla Firefox	','	Mobile	','	happy	');
insert into reviews values(	10507	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10508	,'	Chrome	','	Desktop	','	happy	');
insert into reviews values(	10509	,'	Mozilla	','	Desktop	','	not happy	');
insert into reviews values(	10510	,'	Chrome	','	Desktop	','	happy	');
insert into reviews values(	10511	,'	IE	','	Mobile	','	happy	');
insert into reviews values(	10512	,'	Mozilla Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10513	,'	IE	','	Mobile	','	happy	');
insert into reviews values(	10514	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10515	,'	Chrome	','	Mobile	','	happy	');
insert into reviews values(	10516	,'	Mozilla Firefox	','	Desktop	','	happy	');
insert into reviews values(	10517	,'	Google Chrome	','	Desktop	','	happy	');
insert into reviews values(	10518	,'	IE	','	Mobile	','	not happy	');
insert into reviews values(	10519	,'	Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10520	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10521	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10522	,'	Mozilla	','	Tablet	','	happy	');
insert into reviews values(	10523	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10524	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10525	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10526	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10527	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10528	,'	Opera	','	Desktop	','	happy	');
insert into reviews values(	10529	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10530	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10531	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10532	,'	InternetExplorer	','	Tablet	','	happy	');
insert into reviews values(	10533	,'	Mozilla Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10534	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10535	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10536	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10537	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10538	,'	Mozilla Firefox	','	Mobile	','	happy	');
insert into reviews values(	10539	,'	IE	','	Mobile	','	happy	');
insert into reviews values(	10540	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10541	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10542	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10543	,'	IE	','	Desktop	','	happy	');
insert into reviews values(	10544	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10545	,'	Google Chrome	','	Tablet	','	not happy	');
insert into reviews values(	10546	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10547	,'	Mozilla	','	Tablet	','	not happy	');
insert into reviews values(	10548	,'	Mozilla Firefox	','	Desktop	','	happy	');
insert into reviews values(	10549	,'	IE	','	Desktop	','	happy	');
insert into reviews values(	10550	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10551	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10552	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10553	,'	Internet Explorer	','	Mobile	','	happy	');
insert into reviews values(	10554	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10555	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10556	,'	Opera	','	Mobile	','	happy	');
insert into reviews values(	10557	,'	Chrome	','	Mobile	','	happy	');
insert into reviews values(	10558	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10559	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10560	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10561	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10562	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10563	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10564	,'	IE	','	Mobile	','	happy	');
insert into reviews values(	10565	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10566	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10567	,'	Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10568	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10569	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10570	,'	Chrome	','	Mobile	','	not happy	');
insert into reviews values(	10571	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10572	,'	Internet Explorer	','	Desktop	','	happy	');
insert into reviews values(	10573	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10574	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10575	,'	Edge	','	Tablet	','	happy	');
insert into reviews values(	10576	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10577	,'	Edge	','	Tablet	','	happy	');
insert into reviews values(	10578	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10579	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10580	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10581	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10582	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10583	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10584	,'	Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10585	,'	Opera	','	Desktop	','	happy	');
insert into reviews values(	10586	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10587	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10588	,'	Chrome	','	Mobile	','	happy	');
insert into reviews values(	10589	,'	Google Chrome	','	Desktop	','	happy	');
insert into reviews values(	10590	,'	Internet Explorer	','	Mobile	','	happy	');
insert into reviews values(	10591	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10592	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10593	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10594	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10595	,'	Mozilla	','	Desktop	','	not happy	');
insert into reviews values(	10596	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10597	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10598	,'	Mozilla Firefox	','	Tablet	','	happy	');
insert into reviews values(	10599	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10600	,'	IE	','	Desktop	','	happy	');
insert into reviews values(	10601	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10602	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10603	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10604	,'	Safari	','	Desktop	','	happy	');
insert into reviews values(	10605	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10606	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10607	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10608	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10609	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10610	,'	Mozilla	','	Mobile	','	not happy	');
insert into reviews values(	10611	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10612	,'	InternetExplorer	','	Tablet	','	not happy	');
insert into reviews values(	10613	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10614	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10615	,'	Internet Explorer	','	Tablet	','	happy	');
insert into reviews values(	10616	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10617	,'	Chrome	','	Mobile	','	happy	');
insert into reviews values(	10618	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10619	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10620	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10621	,'	IE	','	Mobile	','	happy	');
insert into reviews values(	10622	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10623	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10624	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10625	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10626	,'	Google Chrome	','	Desktop	','	happy	');
insert into reviews values(	10627	,'	Google Chrome	','	Tablet	','	happy	');
insert into reviews values(	10628	,'	Mozilla Firefox	','	Desktop	','	happy	');
insert into reviews values(	10629	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10630	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10631	,'	Chrome	','	Tablet	','	happy	');
insert into reviews values(	10632	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10633	,'	Edge	','	Tablet	','	happy	');
insert into reviews values(	10634	,'	Internet Explorer	','	Tablet	','	happy	');
insert into reviews values(	10635	,'	Mozilla Firefox	','	Tablet	','	happy	');
insert into reviews values(	10636	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10637	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10638	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10639	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10640	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10641	,'	Mozilla Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10642	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10643	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10644	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10645	,'	IE	','	Tablet	','	happy	');
insert into reviews values(	10646	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10647	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10648	,'	Mozilla Firefox	','	Desktop	','	happy	');
insert into reviews values(	10649	,'	Mozilla Firefox	','	Mobile	','	happy	');
insert into reviews values(	10650	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10651	,'	Chrome	','	Desktop	','	happy	');
insert into reviews values(	10652	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10653	,'	Mozilla	','	Mobile	','	not happy	');
insert into reviews values(	10654	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10655	,'	IE	','	Mobile	','	happy	');
insert into reviews values(	10656	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10657	,'	IE	','	Desktop	','	happy	');
insert into reviews values(	10658	,'	IE	','	Desktop	','	happy	');
insert into reviews values(	10659	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10660	,'	Mozilla Firefox	','	Desktop	','	happy	');
insert into reviews values(	10661	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10662	,'	Edge	','	Tablet	','	happy	');
insert into reviews values(	10663	,'	Mozilla	','	Tablet	','	happy	');
insert into reviews values(	10664	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10665	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10666	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10667	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10668	,'	IE	','	Desktop	','	happy	');
insert into reviews values(	10669	,'	IE	','	Desktop	','	happy	');
insert into reviews values(	10670	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10671	,'	InternetExplorer	','	Tablet	','	happy	');
insert into reviews values(	10672	,'	Mozilla Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10673	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10674	,'	Mozilla	','	Desktop	','	not happy	');
insert into reviews values(	10675	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10676	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10677	,'	Opera	','	Mobile	','	happy	');
insert into reviews values(	10678	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10679	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10680	,'	Chrome	','	Desktop	','	happy	');
insert into reviews values(	10681	,'	Mozilla Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10682	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10683	,'	Mozilla Firefox	','	Desktop	','	happy	');
insert into reviews values(	10684	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10685	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10686	,'	IE	','	Mobile	','	happy	');
insert into reviews values(	10687	,'	Chrome	','	Tablet	','	happy	');
insert into reviews values(	10688	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10689	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10690	,'	Internet Explorer	','	Mobile	','	not happy	');
insert into reviews values(	10691	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10692	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10693	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10694	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10695	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10696	,'	Mozilla Firefox	','	Mobile	','	happy	');
insert into reviews values(	10697	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10698	,'	Google Chrome	','	Tablet	','	happy	');
insert into reviews values(	10699	,'	InternetExplorer	','	Tablet	','	happy	');
insert into reviews values(	10700	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10701	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10702	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10703	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10704	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10705	,'	Mozilla	','	Tablet	','	happy	');
insert into reviews values(	10706	,'	Internet Explorer	','	Tablet	','	happy	');
insert into reviews values(	10707	,'	Safari	','	Mobile	','	happy	');
insert into reviews values(	10708	,'	Google Chrome	','	Desktop	','	not happy	');
insert into reviews values(	10709	,'	Internet Explorer	','	Mobile	','	happy	');
insert into reviews values(	10710	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10711	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10712	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10713	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10714	,'	IE	','	Mobile	','	not happy	');
insert into reviews values(	10715	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10716	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10717	,'	Google Chrome	','	Desktop	','	happy	');
insert into reviews values(	10718	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10719	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10720	,'	Mozilla Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10721	,'	Mozilla Firefox	','	Mobile	','	happy	');
insert into reviews values(	10722	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10723	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10724	,'	Mozilla	','	Tablet	','	happy	');
insert into reviews values(	10725	,'	Mozilla Firefox	','	Desktop	','	happy	');
insert into reviews values(	10726	,'	Mozilla Firefox	','	Mobile	','	happy	');
insert into reviews values(	10727	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10728	,'	Safari	','	Desktop	','	happy	');
insert into reviews values(	10729	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10730	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10731	,'	IE	','	Desktop	','	happy	');
insert into reviews values(	10732	,'	InternetExplorer	','	Tablet	','	happy	');
insert into reviews values(	10733	,'	Mozilla	','	Tablet	','	not happy	');
insert into reviews values(	10734	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10735	,'	Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10736	,'	Mozilla Firefox	','	Tablet	','	happy	');
insert into reviews values(	10737	,'	Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10738	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10739	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10740	,'	Mozilla	','	Tablet	','	happy	');
insert into reviews values(	10741	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10742	,'	Internet Explorer	','	Tablet	','	happy	');
insert into reviews values(	10743	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10744	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10745	,'	Internet Explorer	','	Desktop	','	happy	');
insert into reviews values(	10746	,'	IE	','	Mobile	','	happy	');
insert into reviews values(	10747	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10748	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10749	,'	InternetExplorer	','	Tablet	','	happy	');
insert into reviews values(	10750	,'	Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10751	,'	Mozilla	','	Desktop	','	not happy	');
insert into reviews values(	10752	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10753	,'	Chrome	','	Mobile	','	happy	');
insert into reviews values(	10754	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10755	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10756	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10757	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10758	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10759	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10760	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10761	,'	Mozilla Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10762	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10763	,'	Firefox	','	Desktop	','	happy	');
insert into reviews values(	10764	,'	InternetExplorer	','	Mobile	','	not happy	');
insert into reviews values(	10765	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10766	,'	IE	','	Mobile	','	happy	');
insert into reviews values(	10767	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10768	,'	Edge	','	Mobile	','	not happy	');
insert into reviews values(	10769	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10770	,'	Opera	','	Desktop	','	happy	');
insert into reviews values(	10771	,'	Internet Explorer	','	Mobile	','	happy	');
insert into reviews values(	10772	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10773	,'	Mozilla	','	Desktop	','	not happy	');
insert into reviews values(	10774	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10775	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10776	,'	Edge	','	Tablet	','	happy	');
insert into reviews values(	10777	,'	Internet Explorer	','	Mobile	','	happy	');
insert into reviews values(	10778	,'	Mozilla Firefox	','	Desktop	','	happy	');
insert into reviews values(	10779	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10780	,'	Mozilla	','	Mobile	','	happy	');
insert into reviews values(	10781	,'	Firefox	','	Tablet	','	not happy	');
insert into reviews values(	10782	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10783	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10784	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10785	,'	Edge	','	Tablet	','	not happy	');
insert into reviews values(	10786	,'	Chrome	','	Desktop	','	happy	');
insert into reviews values(	10787	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10788	,'	Mozilla Firefox	','	Mobile	','	happy	');
insert into reviews values(	10789	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10790	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10791	,'	Google Chrome	','	Desktop	','	not happy	');
insert into reviews values(	10792	,'	Google Chrome	','	Tablet	','	happy	');
insert into reviews values(	10793	,'	Edge	','	Desktop	','	not happy	');
insert into reviews values(	10794	,'	Chrome	','	Mobile	','	happy	');
insert into reviews values(	10795	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10796	,'	InternetExplorer	','	Mobile	','	happy	');
insert into reviews values(	10797	,'	Internet Explorer	','	Mobile	','	happy	');
insert into reviews values(	10798	,'	Firefox	','	Tablet	','	happy	');
insert into reviews values(	10799	,'	Chrome	','	Mobile	','	not happy	');
insert into reviews values(	10800	,'	Mozilla Firefox	','	Desktop	','	happy	');
insert into reviews values(	10801	,'	Mozilla	','	Desktop	','	happy	');
insert into reviews values(	10802	,'	Edge	','	Tablet	','	happy	');
insert into reviews values(	10803	,'	InternetExplorer	','	Tablet	','	not happy	');
insert into reviews values(	10804	,'	Mozilla	','	Tablet	','	happy	');
insert into reviews values(	10805	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10806	,'	Mozilla Firefox	','	Tablet	','	happy	');
insert into reviews values(	10807	,'	IE	','	Mobile	','	happy	');
insert into reviews values(	10808	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10809	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10810	,'	Google Chrome	','	Desktop	','	happy	');
insert into reviews values(	10811	,'	Edge	','	Tablet	','	happy	');
insert into reviews values(	10812	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10813	,'	Mozilla Firefox	','	Desktop	','	not happy	');
insert into reviews values(	10814	,'	Firefox	','	Mobile	','	not happy	');
insert into reviews values(	10815	,'	Edge	','	Desktop	','	happy	');
insert into reviews values(	10816	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10817	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10818	,'	Firefox	','	Mobile	','	happy	');
insert into reviews values(	10819	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10820	,'	Google Chrome	','	Mobile	','	happy	');
insert into reviews values(	10821	,'	Google Chrome	','	Desktop	','	happy	');
insert into reviews values(	10822	,'	InternetExplorer	','	Desktop	','	happy	');
insert into reviews values(	10823	,'	Edge	','	Mobile	','	happy	');
insert into reviews values(	10824	,'	Internet Explorer	','	Mobile	','	not happy	');
